### PR TITLE
Add iterator starting at a given value

### PR DESCRIPTION
**Pull request by michaelmior**
This is a follow up to #53 which implements `next_set_bit`on top of an iterator for equal or larger. I'm not sure I'm happy with the naming and I expect the implementation may need some tweaks, but it works :)

### CODE REVIEW

**Comment by Ezibenroc** [comment]
Thank you, great PR!

Correct me if I am wrong, but I think that you can already achieve a similar thing with the `rank()` method and slices:
```python
bm = BitMap(range(0, 100, 3))
for i in range(1, 100):
    assert list(bm[bm.rank(i-1):]) == list(bm.iter_equal_or_larger(i))
    assert bm[bm.rank(i-1)] == bm.next_set_bit(i)
```
So, the main benefits of these new methods are:
- Only one search in the bitmap instead of two
- Lazy evaluation with the iterator for `iter_equal_or_larger`, so more efficient if we do not need all the values (but if we do need all the values as a bitmap, the `rank()` solution is probably much better).

In my first (quick) tests, it seems great for `next_set_bit`:
```python
bm = BitMap(range(0, 100000000, 3))

%timeit bm[bm.rank(1234567-1)]
4.88 µs ± 43.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

%timeit bm.next_set_bit(1234567)
482 ns ± 2.67 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```
For `iter_equal_or_larger`, I do not think there is a fair comparison possible.

----
Before I merge, could you add some documentation for `iter_equal_or_larger`?

**Comment by michaelmior** [comment]
@Ezibenroc Good point that this could be done with `rank` and thanks for the benchmark! I added the extra documentation.

**Comment by Ezibenroc** [comment]
Thanks!

**Comment by michaelmior** [comment]
Thanks for the merge!

**Pull request merged**
