### PR TITLE
better documentation and portability

### PR DESCRIPTION
**Pull request by lemire**
With these changes, I am able to use the code on a Mac.

Feel free not to merge... but I think that a few ideas are useful.

### CODE REVIEW

**Comment by Ezibenroc** [comment]
Thanks !
It seems possible to also test for OSX on Travis (https://docs.travis-ci.com/user/multi-os/). Do you want to add it before I merge?

**Comment by lemire** [comment]
@Ezibenroc 

I do not yet know how to run your tests manually on a Mac. I can install Python 3. I can install hypothesis on the existing Python 2.7 that is the default on Macs... But I do not know yet how to install hypothesis for a freshly installed Python 3 on Mac.

It is probably a silly thing... but...

**Comment by Ezibenroc** [comment]
Is pip available on OSX for python3?

Then, it would simply be this:
```bash
pip3 install --user hypothesis
```

**Comment by lemire** [comment]
That works.

**Comment by lemire** [comment]
You probably can get cmake installed this way...

```
brew install cmake
```

**Comment by lemire** [comment]
Ah. No need for cmake because it is already there... supposedly.

**Comment by lemire** [comment]
Could be made to run tests on Macs... but I don't know how. I can't even pass your unit tests on my local Mac...

**Comment by Ezibenroc** [comment]
What is the issue on your local Mac?

**Comment by lemire** [comment]
```bash
$ python3 test.py
Segmentation fault: 11
```

**Comment by lemire** [comment]
I suspect that you have to specify the return type of functions. Or something.

**Comment by Ezibenroc** [comment]
Oh. Maybe it is related to https://github.com/Ezibenroc/PyRoaringBitMap/issues/2 then. It seems the issue was indeed specifying the return and argument types of the functions. I am currently working on it.

**Comment by Ezibenroc** [comment]
I will merge your branch now, we will add OSX on Travis later.

**Comment by lemire** [comment]
Yes. I'm eager to help. Just ping me.

**Pull request merged**
