### PR TITLE
Packaging and release tweaks and maintenance 

### PR DESCRIPTION
**Pull request by SamHames**
As discussion started in #78 

Major changes:

- Migrate from the custom project amalgamation to the official CRoaring release amalgamation via a simple download script that retrieves a tagged release version of `roaring.c` and `roaring.h`.
- Vendor the roaring sources (`roaring.c` and `roaring.h`) to make the repository stand alone.
- Migrate from a c/c++ only source distribution to a Cython source distribution: Cython is now a setup time dependency for source installations.
- Build wheels with cibuildwheel and github actions for Windows, Linux and Mac (Intel and Arm) for all currently supported CPython's (3.7 - 3.11).  

Minor changes:

- tests can now also be run in an isolated environment via tox
- the version information is simplified down to just the pyroaring version and croaring release version. We're only using tagged releases of croaring so the release number is sufficient.
- `version.pxi` is now the source of truth for the package version (in the source anyway). This removes  the `setup.py` side effect of writing a file.
- the croaring_version is specified as the single line file in `croaring_version.pxi`, just to keep the amalgamation download script as simple as possible
- the `print_platform` function is removed - I'm not sure we want to rely on exposing that anyway as it doesn't seem to be part of the public API of CRoaring...
- roaring.c and roaring.h are maked as `-diff` in `.gitattributes` so that changes in those files don't ever pollute a diff

### CODE REVIEW

**Comment by Ezibenroc** [comment]
Great works, thanks!

Some first comments, maybe more will come later.

First, about the files included in the git repository:
- I find it odd to include croaring source in the git (files `croaring.c` and `croaring.h`). My main concern is that future commits could be less readable, because small changes in pyroaring side would be hard to spot next to the larger changes in croaring. This is avoidable if we make sure to never upgrade croaring in the same commit as a legit change in pyroaring, but then the codebase might be in an inconsistent state for a given commit (e.g. tests might be broken at this intermediate commit). Also, the same concern applies at the scale of a whole pull request, and at this level we might not be able to separate croaring update from the other changes.
- Same concern for the Cython generated file (`pyroaring.cpp`). Here this is even worse, since this file is huge, and minor changes in the Cython code sometimes lead to huge changes in this file.

So, is there a reason why you wanted these files in the git repository? For instance, we could use `download_amalgamation.py` in the Github action to grab croaring source.
The thing is, I do not see the gain of including these files.

I think it is a small regression that the file `version.pxi` is not automatically generated. This is yet another file that we should not forget to modify whenever we do a release. What is your motivation for removing this file generation from `setup.py`?
Note that I don't mind about losing the git SHA1 (e.g. variable `__git_version__`), this one was not that useful in practice.

Minor nitpick: it would be good to rebase your commits before merging, to have a cleaner history. For instance, squash/remove commits bead8ae0ca9045684edffb084a922d426cae00f6, 249e57b9037fea30fe8f34f366731dd6d3c19b4e and 02d75b1b444a0063152f2497a39b2d33c5f605d9. But this can wait.

**Comment by urdvr** [comment]
Hi, I've been following the comments as an interested bystander and figured I'd throw in my two cents. There is a lot of good work in this PR that is worth discussing.

It makes a lot of sense to me to use the official amalgamation and to commit these files explicitly to the repo. I think it's good that the CRoaring code is explicitly tracked in the repository. Previously it was tracked as a submodule, now it would be tracked as explicitly vendored files. (From my point-of-view, in an ideal world there would be a CRoaring repository that contains the amalgamation and it could be tracked as a submodule instead of using a custom script.)

---

I don't understand the reasoning to commit the pyroaring.cpp file though. Generally I try to commit and track all inputs to a build process and leave all build artifacts out of the repository. And I'd consider pyroaring.cpp to be a build artifact.
 
My objections to committing pyroaring.cpp would be:
- I don't understand the value of making cython an optional part of the build; 
- I think it might lead to confusion and accidental bugs in the release process (changing code, forgetting to generate pyroaring.cpp);
- The file is 1.5MB at the moment and will unnecessarily balloon the repository size with each change

---

The version.pxi and croaring_version.pxi changes confuse me as well and I couldn't quickly figure out why these changes are useful. 

---

Again, there are a lot of good and useful changes here. I think this PR has grown out of the scope of "tweaks" though. Maybe it would be a good idea to split it up into a couple of separate PR-s which could be analyzed independently?

**Comment by Ezibenroc** [comment]
> Any objections to me just squashing the whole changeset into one commit just before we merge? That will probably be more readable than trying to cleanup the history especially if we change course on some of the decisions.

Sure, no problem!

> A brief apology too - I realise now based on your questions that I've made some bigger changes than I first understood and it would have been better to discuss first rather than surprising you.

No worries, it is also nice to have some code to discuss.

> As for what's included my rationale was to make the repository:

> 1. Stand on it's own [...]
> 2. Match exactly what is tested, packaged and shipped [...]
> 3. Explicitly manage which version of CRoaring is present [...]

Well, (3) could also be achieved with your `download_amalgamation.py` script. But I understand (1) and it is a valid point. 
As for (2), I am not sure this is a big problem if the code generated by Cython on your PC is not exactly identical to the one generated by the CI. We want to assume that Cython has no bug, so if it generates two outputs that are not byte-identical, we can still assume that they are equivalent.

@urdvr makes very good points about `pyroaring.cpp`. I think that a good rule of thumb is to **not** commit files automatically generated, except if there is a very good reason. For instance, in C/C++ projects, we usually do not commit the binaries produced by the compiler. Likewise, I find it odd to commit `pyroaring.cpp`, and I do not understand the benefit, since a pyroaring developer would need Cython anyway and a simple user would just install the package.
For the same "rule" of not committing generated files, I also find it weird to commit `roaring.c` and `roaring.h`. But here you make a valid point to have a standalone repository, so I could agree to this change.

> Again, there are a lot of good and useful changes here. I think this PR has grown out of the scope of "tweaks" though. Maybe it would be a good idea to split it up into a couple of separate PR-s which could be analyzed independently?

It could be tricky to split though. I think it is fine as a single PR.

**Comment by Ezibenroc** [comment]
Ok, I understand your concern. At some point we had no wheels on pypi, only the source package, so we needed to include `pyroaring.cpp` to get rid of the cython dependency for the users. But now, the preferred installation method is with the wheels which work pretty well out of the box.
So I am fine with removing `pyroaring.cpp` from the `*.tar.gz` package and asking users to get Cython if they really want to install pyroaring this way.

**Comment by Ezibenroc** [comment]
> Do you have any other questions or concerns (such as about the github actions[1](https://github.com/Ezibenroc/PyRoaringBitMap/pull/79#user-content-fn-1-07e4dff25032c4f0585811289d92fd38) changes)? If not I'll go ahead and squash and write up a proper summary of the changes.

Nope, this is great, I really like what you did with the github actions!

**Comment by Ezibenroc** [comment]
Awesome, thanks a lot!

**Pull request merged**
