### PR TITLE
Version 1.0.0

### PR DESCRIPTION
**Pull request by lemire**
This version introduces support for AVX-512 optimizations. On recent Intel and AMD hardware (Zen 4, Ice Lake), one might see better performance for some workloads.

The AVX-512 support was provided by @huihan365

### CODE REVIEW

**Comment by Ezibenroc** [comment]
Awesome, thanks!

**Comment by Ezibenroc** [comment]
Hey @lemire (and @huihan365), what kind of performance improvement would you expect from this? Wouldn't we aim for a x2 improvement in the best cases (like the union of two dense bitmaps)?

I am a bit underwhelmed so far. I ran some benchmarks on an AWS `c6i.large` instance (Intel Ice Lake, namely a Xeon Platinum 8375C) and dit not observe anything spectacular. You can have a look at the [plots](https://github.com/Ezibenroc/PyRoaringBitMap/blob/benchmarking/version_evaluation.ipynb) and the [data](https://github.com/Ezibenroc/PyRoaringBitMap/blob/benchmarking/data/version_evaluation_2023-03-26.csv).

As a quicker benchmark, you can also run this:
```
pip uninstall pyroaring
pip install pyroaring==0.4.0
python -c 'import timeit ; print(timeit.timeit(setup="from pyroaring import BitMap ; bm1 = BitMap(range(0, 1000000, 2)) ; bm2 = BitMap(range(1, 1000000, 2))", stmt="bm3 = bm1 | bm2"))'
```
Compare pyroaring 0.4.0 (which has AVX512) with an earlier version (typically 0.3.8). You can also change the bitmap operation to something else, e.g. `bm1 & bm2`.
With this one, I only observed a 10% gain between 0.3.8 and 0.4.0.

I am not super familiar with AWS, so I don't know if there are some kind of limitations.

**Comment by lemire** [comment]
Thanks for running the benchmarks.

Going from 256-bit AVX2 to 512-bit AVX-512, you go from three execution units to two execution units, and you have ` 2*512/(3*256.0) == 1.333 `. The widening itself is not going to do anything like double the performance *in general*. Furthermore, only *some* operations are accelerated with SIMD... so in any benchmarking, the changes would only affect some of the code... Furthermore, we did not do much tuning on the AVX-512 code. And, finally, there are several operations which we did not optimize for AVX-512, but could have. Plus, our AVX2 was already quite optimized at times.


I don't want to undersell the work... @huihan365 did great work. But could we go further? Yes. With AVX-512, you can sometimes achieve *much more than 2x* the performance like, possibly a 3x gain for some operations, e.g., see https://lemire.me/blog/2022/05/10/faster-bitset-decoding-using-intel-avx-512/ The reason you can gain much more than the theoretical 2x is that AVX-512 is filled with fancy instructions that can have magical performance if they are well suited to the problem at hand.

In fact, and let us be clear about that, AVX-512 is not really about 512 bits... it is very much about the fancy new instructions, many of which are used by @huihan365 already, like vectorized compress and vectorized popcnt.

This release, and the hard work done by @huihan365 opens the door for further great work. Now that we have the general code architecture to support AVX-512, we can throw in more operations, and optimize the ones that we have.

The key to understanding my message is that many things that could not be fruitfully vectorized before AVX-512 can now be. In this release, we don't go there. I don't think we vectorize anything new. This can be done in the future.

If you are interested... come and join us in C land... the code is quite sensible... :-)

**Comment by Ezibenroc** [comment]
Alright, thank you for the explanations, very clear!

> If you are interested... come and join us in C land... the code is quite sensible... :-)

I already have troubles reading AVX code, I am not sure I could write it. But it could be fun to try yes ;-)

**Pull request merged**
