### PR TITLE
Proposal: drop numpy dependency (simpler, faster code).

### PR DESCRIPTION
**Pull request by lemire**
The current code relies on ``numpy`` for one tiny operation that seems unwarranted. On my machine, it is about half the speed of a good old ``ctype`` array. 

I propose to simplify the code to remove a nagging dependency and to improve the performance.

Of course, ``numpy`` is pretty good at checking that integers are in a given range, but it is not perfect. If, for some reason, an integer cannot be converted to a machine word, we get an ugly ``OverflowError``.

```python
>>> values = [1<<100]
>>> c_array = numpy.ascontiguousarray(values, dtype=numpy.int64)
Traceback (most recent call last):
"/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/numeric.py", line 548, in ascontiguousarray
    return array(a, dtype, copy=False, order='C', ndmin=1)
OverflowError: Python int too large to convert to C long
```

With a standard Python array, you can just cast on the least significant 32 bits. That's perfectly "safe" and predictable. What if the programmer tries to use values above 32 bit? Some of its vallues will get casted... but that's not different from, say, ``numpy``'s default behavior:

```python
>>> numpy.ascontiguousarray([1<<34],dtype=numpy.uint32)
array([0], dtype=uint32)
```
That's going to work just fine, outputting a zero. I don't think that this is a bug-prone behavior. It is just a cast.

Now, if you must, you can easily provide a convenience function allowing the user to check whether its values are "safe" 32-bit integers.

One last note... I did not check it, but I think that your ``check_value`` function can be simplified to be something like ``(x >> 32) == 0``. I suspect it is going to be faster. (I don't think there is any need of checking the type.)

### CODE REVIEW

**Comment by Ezibenroc** [comment]
Thank you. This is a good point, I think that the performance loss is to high to be worth the small bug avoidance, especially if we provide a convenience function.

Can you please fix the merge conflict? Sorry for that, I should have waited for my last commit.
Can you also remove the code you commented?

**Comment by lemire** [comment]
@Ezibenroc 

Conflict resolved.

**Comment by Ezibenroc** [comment]
You left some garbage text written by git, which makes the tests fail (introduced in https://github.com/Ezibenroc/PyRoaringBitMap/pull/8/commits/55310f163f5621592740dec2a1bb73264d6913b0).

**Comment by lemire** [comment]
Sorry. I am away on vacation. I will fix my mistake as soon as I come back.

**Comment by lemire** [comment]
@Ezibenroc 

Should be ok now. Note that I have removed ``numpy`` from the travis script as it is no longer needed.

**Comment by lemire** [comment]
It seems to pass the unit tests.

**Comment by Ezibenroc** [comment]
Thank you, I am merging.

**Pull request merged**
