### PR TITLE
WIP: Windows support

### PR DESCRIPTION
**Pull request by cjmay**
This is a work in progress of the Windows support component of #28.  Feel free to close or delete, but I wanted to provide a tip that I started work on this.

### CODE REVIEW

**Comment by cjmay** [comment]
Also see the appveyor build status: https://ci.appveyor.com/project/cjmay/pyroaringbitmap

**Comment by Ezibenroc** [comment]
Supporting Windows would be great, thank you for your help.

Maybe a first step would be to support the installation from pip? The sources distributed on Pypi (file [pyroaring.tar.gz](https://files.pythonhosted.org/packages/ff/b2/02780d9ab42d1348a77a82481ddf5082bd38e9c025ce228f3a666a8df0c4/pyroaring-0.1.7.tar.gz)) have already passed through some parts of the installation process:
- amalgamation script
- prepare_dist script
- compilation from cython to C++

The "only" remaining part is to compile from C++.

I did quite a lot of modifications in the last version. Everything is now pushed to master, but it seems there are some conflicts on your fork, sorry for that.

**Comment by Ezibenroc** [comment]
I translated `amalgamation.sh` and `prepare_dist.sh` to pure Python in e5ce43de909ffcbeaa757e47898fd177a4b688ef, thus removing the dependency to bash. It should be easier to provide Windows support now, even for the cython → C++ part.

**Comment by cjmay** [comment]
Dumping some relevant-looking links for later:

* https://github.com/theochem/python-cython-ci-example
* https://www.appveyor.com/docs/packaging-artifacts/
* https://stackoverflow.com/a/1387228
* https://github.com/cython/cython/wiki/CythonExtensionsOnWindows#using-windows-sdk-cc-compiler-works-for-all-python-versions
* https://wiki.python.org/moin/WindowsCompilers
* https://blogs.msdn.microsoft.com/vcblog/2016/06/07/standards-version-switches-in-the-compiler/
* https://msdn.microsoft.com/en-us/library/k1ack8f1.aspx

**Comment by cjmay** [comment]
I'm not sure the compiler knows the file is C++ source.  It fails at an initialization list:

```
pyroaring\roaring.cpp(734): warning C4244: '=': conversion from '__int64' to 'int32_t', possible loss of data
pyroaring\roaring.cpp(735): warning C4244: '=': conversion from '__int64' to 'int32_t', possible loss of data
pyroaring\roaring.cpp(736): warning C4244: '=': conversion from '__int64' to 'int32_t', possible loss of data
pyroaring\roaring.cpp(737): warning C4244: '=': conversion from '__int64' to 'int32_t', possible loss of data
pyroaring\roaring.cpp(760): warning C4244: '=': conversion from '__int64' to 'int32_t', possible loss of data
pyroaring\roaring.cpp(761): warning C4244: '=': conversion from '__int64' to 'int32_t', possible loss of data
pyroaring\roaring.cpp(785): warning C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data
pyroaring\roaring.cpp(805): warning C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data
pyroaring\roaring.cpp(817): warning C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data
pyroaring\roaring.cpp(3014): warning C4267: '=': conversion from 'size_t' to 'int32_t', possible loss of data
pyroaring\roaring.cpp(4792): error C2059: syntax error: '.'
. . .
```

The overall first warning/error in the output is the following, but this doesn't seem directly related to that error message

```
pyroaring\pyroaring.pyx: cannot find cimported module 'croaring'
```

**Comment by cjmay** [comment]
As far as I can tell, if the compiler is using C++, the default standard is C++11, which seems to be what CRoaring expects/requires.

**Comment by cjmay** [comment]
I think the problem may actually be that designated initializers are not valid C++11: https://stackoverflow.com/questions/18731707/why-does-c11-not-support-designated-initializer-lists-as-c99 ?

But if that is the case it is somewhat perplexing / frustrating that it works on Linux.

**Comment by cjmay** [comment]
Removing the designators from the CRoaring---and also removing the parentheses around the types that are being initialized---removes the errors.

**Comment by cjmay** [comment]
I opened an issue for a fix/for help: https://github.com/RoaringBitmap/CRoaring/issues/146

**Comment by lemire** [comment]
I think that the problem is with the Python amalgamation script. It generates a file called roaring.cpp, which suggests to the compiler that it is dealing with a C++ source file whereas CRoaring is a C library.

I have opened an issue...

https://github.com/Ezibenroc/PyRoaringBitMap/issues/31

Please get back in touch with me if it fails even after you have renamed roaring.cpp to roaring.c.

Please check my demo that should convince you that CRoaring amalgamated works under Visual Studio...

https://github.com/lemire/croaringfun

**Comment by lemire** [comment]
With some luck, this PR will fix the issue:

https://github.com/Ezibenroc/PyRoaringBitMap/pull/32

**Comment by lemire** [comment]
@cjmay I have issued a PR against your PR and it solves the build problem...

https://ci.appveyor.com/project/cjmay/pyroaringbitmap/build/11-windows

You still have a failure, but it is because hypothesis is not recognized, which is something else. The C/C++ appears to build.

**Comment by cjmay** [comment]
Thanks so much @lemire!

**Comment by cjmay** [comment]
This branch has been rebased off #32.

**Comment by Ezibenroc** [comment]
Sorry for the mess, I have merged #32.

**Comment by lemire** [comment]
This fails maybe because it appears to ignore the problem solved by these lines:

```
if platform.system() != "Darwin":
   compile_args.append('-std=c99')
```

We want to compile with at least C99. Visual Studio provides this and so does the clang compiler in macOS. However many Linux distributions ship with an obsolete GNU GCC compiler... that does not default on C99 or better. Note that C99 means 1999... not exactly bleeding edge.

**Comment by cjmay** [comment]
@lemire thanks for the check!  I had not been paying attention to the travis build.

**Comment by cjmay** [comment]
not to mention the diagnosis :)

**Comment by Ezibenroc** [comment]
It seems the Windows build is working for Python3, that's great!

Do you know what is the issue with the Python2 tests? If I understood well, you have to manually download and install a compiler for this case?

Also, I really don't understand what happens with the 32-bit tests. For the record, this is failing:
```python
bm = BitMap(range(0, 8193, 2), copy_on_write=False)
assert bm.max() == 8192 # fail, bm.max() returns 8224 here
```
My laptop and Travis are 64-bit, so this is difficult for me to test on a 32-bit CPU.
Last time I checked on a Raspberry Pi, the tests were passing, but it was quite a long time ago.

**Comment by cjmay** [comment]
I've made some progress, but I'm a little stuck now.

The [Travis build](https://travis-ci.org/cjmay/PyRoaringBitMap) is back to normal.  The [Appveyor build](https://ci.appveyor.com/project/cjmay/pyroaringbitmap) is modeled after the travis build.  It now succeeds for Python 3.4, 3.5, 3.6 on 64-bit platforms with VS 2017.  It fails for Python 2.7 because Python 2.7 is built with VS 2008 (MS Visual C++ 9.0), which doesn't support C++11, and it seems we need to use the same compiler as was used to build Python.  It also fails for 32-bit platforms at [SelectRankTest.test_max](https://github.com/Ezibenroc/PyRoaringBitMap/blob/7081ceba18ccaf2ee80d3c142e6e612cf77d17d2/test.py#L293); the last three lines of the stack trace are:

```
  File "test.py", line 296, in test_max
    self.assertEqual(bitmap.max(), max(values))
AssertionError: 8224 != 8192
```

The Appveyor build---for the environments that succeed---stores the source and binary wheels as artifacts.  I did a sanity check of the [64-bit Python 3.6 artifacts](https://ci.appveyor.com/project/cjmay/pyroaringbitmap/build/job/5fkr0behagk1r6wd/artifacts) (by downloading, installing, and running `test.py` locally)

**Comment by lemire** [comment]
Hmmm... here is what I did. I wrote this C program...

```
#include <stdio.h>
#include "roaring.c"
int main() {
  roaring_bitmap_t *r1  = roaring_bitmap_from_range(0, 8193, 2);
  printf("max = %d \n", roaring_bitmap_maximum(r1));
  roaring_bitmap_free(r1);
  return 0;
}
```

then I compiled it in 32 bits...

```bash
gcc-6 -O3 -m32 -std=c11  -o testme test.c -march=i386 && ./testme
qemu-i386 ./testme
```

And the output is 8192, as expected.

**Comment by cjmay** [comment]
I started writing my previous comment a while ago and didn't see @Ezibenroc's comment---it's rather redundant now. :)

I'm not sure what's happening in the 32 bit case.  This thread suggests that platform might not actually give us a 32 bit machine/OS: https://help.appveyor.com/discussions/questions/213-platform-x86-is-not-32-bit but it's old, and I'm not sure I'm interpreting it correctly.  I also have a 32 bit machine/OS.

In the Python 2.7 case, I had originally tried building/testing with the same compiler as before and got an error message pointing me to the Visual C++ 9.0 compiler that the build is now downloading for that case: https://ci.appveyor.com/project/cjmay/pyroaringbitmap/build/24-windows/job/krftyuid80m0tpcq

```
python setup.py build_ext -i
Building pyroaring from Cython sources.
pyroaring\pyroaring.pyx: cannot find cimported module 'croaring'
Compiling pyroaring\pyroaring.pyx because it changed.
[1/1] Cythonizing pyroaring\pyroaring.pyx
running build_ext
building 'pyroaring' extension
error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27
Command exited with code 1
```

**Comment by lemire** [comment]
@cjmay 

Is there any reason for your YAML file to differ so much from what is apparently the recommended setup?

Here is what it says...

> Appveyor includes by default all of the compiler toolchains needed to build extensions for Python. For Python 2.7, 3.5+ and 32-bit versions of 3.3 and 3.4, the tools work out of the box. But for 64-bit versions of Python 3.3 and 3.4, there is a small amount of additional configuration needed to let distutils know where to find the 64-bit compilers. 

The recommended setup is apparently this...

https://packaging.python.org/guides/supporting-windows-using-appveyor/

```yaml
environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install wheel"

build: off

test_script:
  # Put your test command here.
  # If you don't need to build C extensions on 64-bit Python 3.3 or 3.4,
  # you can remove "build.cmd" from the front of the command, as it's
  # only needed to support those cases.
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python version you want to use on PATH.
  - "build.cmd %PYTHON%\\python.exe setup.py test"

after_test:
  # This step builds your wheels.
  # Again, you only need build.cmd if you're building C extensions for
  # 64-bit Python 3.3/3.4. And you need to use %PYTHON% to get the correct
  # interpreter
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
```

**Comment by lemire** [comment]
@cjmay 

The recommended setup does not specify a compiler, presumably letting appveyor choose the setup, whereas you apparently force a specific version of visual studio.

**Comment by cjmay** [comment]
@lemire I started with that but it became error-prone and somewhat redundant, as we have platform-specific and Python version-specific adjustments to the build that go beyond the DISTUTILS_USE_SDK flag mentioned in that template.  I got the same errors when the configuration was based on that template.  I simplified it based on this example: https://github.com/theochem/python-cython-ci-example/blob/master/.appveyor.yml

**Comment by lemire** [comment]
@cjmay  Ok. Sounds good.

**Comment by cjmay** [comment]
@lemire as specified in the docs (https://www.appveyor.com/docs/lang/cpp/ -> https://www.appveyor.com/docs/build-environment/#build-worker-images), appveyor picks VS 2015 by default.

**Comment by lemire** [comment]
Oh. I think I know why we get failures on 32-bit Windows. If you look closely, you will notice that there is a warning discouraging you from doing this.

**Comment by lemire** [comment]
Part of the problem is that I don't have a 32-bit Windows handy to test... so here is the problematic code...

```
/* wrappers for Visual Studio built-ins that look like gcc built-ins */
/* result might be undefined when input_num is zero */
static inline int __builtin_ctzll(unsigned long long input_num) {
    unsigned long index;
#ifdef _WIN64  // highly recommended!!!
    _BitScanForward64(&index, input_num);
#else  // if we must support 32-bit Windows
    if ((uint32_t)input_num != 0) {
        _BitScanForward(&index, (uint32_t)input_num);
    } else {
        _BitScanForward(&index, (uint32_t)(input_num >> 32));
        index += 32;
    }
#endif
    return index;
}
```

**Comment by lemire** [comment]
This is entirely untested because I don't have a 32-bit Windows.

I am not sure why anyone is using 32-bit Windows at this point in time. Surely we have retired the 16-bit app by now?

**Comment by lemire** [comment]
Ah. That's probably not the one causing problem... It is probably this function:

```
/* result might be undefined when input_num is zero */
static inline int __builtin_clzll(unsigned long long input_num) {
    unsigned long index;
#ifdef _WIN64  // highly recommended!!!
    _BitScanReverse64(&index, input_num);
#else  // if we must support 32-bit Windows
    if (input_num > 0xFFFFFFF) {
        _BitScanReverse(&index, (uint32_t)(input_num >> 32));
    } else {
        _BitScanReverse(&index, (uint32_t)(input_num));
        index += 32;
    }
#endif
    return 63 - index;
}
```

**Comment by lemire** [comment]
Right. I think that this code is wrong. It is not the 32 bit part per se that is the problem, it is our use of 32-bit Windows intrinsic. I'll push a fix.

**Comment by cjmay** [comment]
I built a branch that tries to follow the Python packaging recommendations more closely, for comparison, but I'm having other problems there.  In particular, it looks like maybe the C syntax support has changed between VS 2015 and VS 2017?

https://ci.appveyor.com/project/cjmay/pyroaringbitmap/build/45-windows-recommended

**Comment by lemire** [comment]
CRoaring passes everything on Visual Studio (both 32-bit and 64-bit, with and without AVX):

https://ci.appveyor.com/project/lemire/croaring

**Comment by lemire** [comment]
@cjmay If you go back to this build...

https://ci.appveyor.com/project/cjmay/pyroaringbitmap/build/39-windows

It should now mostly work, except, of course, for the Python 2 stuff. Not sure about that given that they say it should work.

**Comment by lemire** [comment]
@cjmay 

Is there any particular reason you want to support Python 2.7?

I mean... Python 3.0 was released 10 years ago.

As far as I can tell, major projects like Pytorch have dropped support for Python 2.7 under Windows.

To me, it is already crazy that we are supporting Windows 32-bit. That's for 16-bit app support... were you guys even alive when the last 16-bit apps were written??? I was but I am old.

We need to move forward at some point.

Anyhow, Python 3.x support under Windows would be  a lot better than nothing.

**Comment by lemire** [comment]
@cjmay This looks wrong...

```
  - ps: |
       if ($env:py_version -eq "27") {
         Invoke-WebRequest https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi -OutFile vc27.msi
         msiexec /q /i vc27.msi
       }
   - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%'
```

For 2.7, you should be calling

```
C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\vcvarsall.bat
```

I am also not sure that vcvarsall.bat gets x64 parameters... I think it needs amd64:

https://msdn.microsoft.com/en-us/library/f2ccy3wt.aspx

**Comment by Ezibenroc** [comment]
Thank you @lemire for your quick fix with the 32-bit build!

@cjmay, I am fine with not supporting Python 2 on Windows if it is too much trouble, I think our effort should focus on Python 3. What do you think ?

Could you also add a few explanations in the README on how to build pyroaring from source on Windows?

**Comment by cjmay** [comment]
@lemire excellent!!  Thank you so much for looking so deeply into the error, and fixing it so quickly, I never would have figured that out.

I don't develop very much on Windows, so I didn't know how prevalent 32-bit platforms were (or weren't!), but I am/have been hoping to be as platform-friendly as I can.  I work with a lot of research code that often has specific---sometimes very new, sometimes very old---dependencies, in particular a lot of Python 2.7 code, and I find it's frustrating when I'm forced to refactor or abandon a project because of incompatibilities.  I definitely prefer using Python 3, and prefer when other projects support Python 3, but I'd also like to help out developers stuck with Python 2.7 if I can!

I agree in any case that we've made a lot of progress, there is so much green now!  https://ci.appveyor.com/project/cjmay/pyroaringbitmap/build/47-windows

**Comment by lemire** [comment]
I am more optimistic that we can get close to supporting Python 2.7.

**Comment by lemire** [comment]
@cjmay Feel free to persist but, honestly, it seems perfectly reasonable to just say that Python 2.7 is unsupported. I was more hopeful at some point, but the more I look at this the more it looks backward.

There is simply no good reason for people not to update to Python 3.x at this time. Python 2.7 is reaching end of life in 2020. It is no longer going to be supported. 

The fact that appveyor does not provide, out of the box, the proper version of Visual Studio, and that you need to download a super old Visual Studio is quite bad.

**Comment by lemire** [comment]
@cjmay Are you sure that the visual studio thingy gets installed?

**Comment by cjmay** [comment]
@lemire, you are right, the Visual C++ 9.0 compiler for Python 2.7 was not completely installed before proceeding with the rest of the build.  The build environment for Python 2.7 was misconfigured as well.  I have now hit a new issue, that the compiler cannot find stdint.h or stdbool.h.  [Other people have worked around this by pointing the compiler to the headers from a more recent distribution of Visual Studio](https://github.com/MrGF/py-faster-rcnn-windows/issues/3).  However, when I tried this with VS 2017, nothing seemed to happen (I got the same error message as without the fix).  I am working on it now, but I am not very optimistic, as I think VS 2008 (= 9.0) does not support C++11, and CRoaring/PyRoaring appears to require it.

**Comment by lemire** [comment]
@cjmay 

You have obviously worked very hard. I think it is reasonable to say "on Windows, you need Python 3.4 or better".

Anyhow, people need to move on. We are not just going to keep using Visual Studio 2008 until the end of times.

**Comment by cjmay** [comment]
I am giving up on Python 2.7 support, but I left the most recent attempt in the commit history (10bc761 via 34bc98e) in case anyone wants to pursue it.

**Comment by Ezibenroc** [comment]
This looks great, thanks a lot for your work!

I will merge this branch and setup the automatic deployment of the wheels to Github releases.

**Pull request merged**
